/**
 * exportUtils.ts
 * Client-side CSV and PDF export for Screening Mode results.
 * No file bytes pass through a server route.
 */

import type { MatchResult, RiskTier } from '@/types/screening';
import { RECOMMENDED_ACTIONS, TIER_COLORS } from '@/types/screening';

// ─── Tier order for PDF sort ──────────────────────────────────────────────────

const TIER_ORDER: Record<RiskTier, number> = {
  EXACT: 0, HIGH: 1, MEDIUM: 2, LOW: 3, CLEAR: 4,
};

// ─── Hex → RGB (for jspdf color calls) ───────────────────────────────────────

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.replace('#', ''), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

// ─── CSV Export ───────────────────────────────────────────────────────────────

const CSV_HEADERS = [
  'Input Name',
  'Normalized Input',
  'Matched SDN Name',
  'SDN ID',
  'Entity Type',
  'Region',
  'Country',
  'JW Score',
  'DM Bonus',
  'TSR Score',
  'Composite Score',
  'Match Algorithm',
  'Risk Tier',
  'Effective Tier',
  'Name Length Penalty',
  'Transformation Detected',
  'Recommended Action',
];

function csvEscape(value: string | number | boolean | null | undefined): string {
  const str = value === null || value === undefined ? '' : String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function exportCsv(results: MatchResult[], filename = 'ofac-screening-results.csv') {
  const sorted = [...results].sort((a, b) => TIER_ORDER[a.effectiveTier] - TIER_ORDER[b.effectiveTier]);

  const rows = sorted.map((r) => [
    r.inputName,
    r.normalizedInput,
    r.matchedSdnName,
    r.sdnId,
    r.entityType,
    r.region,
    r.country ?? '',
    r.jwScore.toFixed(4),
    r.dmBonus.toFixed(4),
    r.tsrScore.toFixed(4),
    r.compositeScore.toFixed(4),
    r.matchAlgorithm,
    r.riskTier,
    r.effectiveTier,
    r.nameLengthPenaltyApplied ? 'Yes' : 'No',
    r.transformationDetected ? 'Yes' : 'No',
    RECOMMENDED_ACTIONS[r.effectiveTier],
  ]);

  const lines = [CSV_HEADERS, ...rows].map((row) => row.map(csvEscape).join(',')).join('\r\n');

  // UTF-8 BOM so Excel opens non-Latin characters correctly
  const bom = '\uFEFF';
  const blob = new Blob([bom + lines], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── PDF Export ───────────────────────────────────────────────────────────────

// Crowe brand values
const CROWE_INDIGO = '#002E62';
const CROWE_AMBER  = '#F5A800';
const DISCLAIMER =
  'This report was generated by the Crowe OFAC Sensitivity Testing tool for internal compliance ' +
  'review purposes only. It does not constitute legal advice or a definitive OFAC compliance ' +
  'determination. Results should be reviewed by a qualified compliance officer before taking action.';

export async function exportPdf(results: MatchResult[], filename = 'ofac-screening-report.pdf') {
  // Lazy-import jspdf + autotable to keep initial bundle small
  const { jsPDF } = await import('jspdf');
  const autoTable = (await import('jspdf-autotable')).default;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  // Attempt to load NotoSans for Unicode support (Arabic, Cyrillic)
  // Font must be present at /fonts/NotoSans-Regular.ttf in the public directory.
  let unicodeFontLoaded = false;
  try {
    const resp = await fetch('/fonts/NotoSans-Regular.ttf');
    if (resp.ok) {
      const buffer = await resp.arrayBuffer();
      const base64 = btoa(
        new Uint8Array(buffer).reduce((data, byte) => data + String.fromCharCode(byte), '')
      );
      doc.addFileToVFS('NotoSans-Regular.ttf', base64);
      doc.addFont('NotoSans-Regular.ttf', 'NotoSans', 'normal');
      unicodeFontLoaded = true;
    }
  } catch {
    // Font unavailable — fall back to Helvetica (Latin only)
  }

  const fontName = unicodeFontLoaded ? 'NotoSans' : 'helvetica';

  const pageWidth  = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const now        = new Date().toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' });

  const sorted = [...results].sort((a, b) => TIER_ORDER[a.effectiveTier] - TIER_ORDER[b.effectiveTier]);

  // ── Header band ──────────────────────────────────────────────────────────────

  function drawHeader(pageNumber: number) {
    const [ir, ig, ib] = hexToRgb(CROWE_INDIGO);
    const [ar, ag, ab] = hexToRgb(CROWE_AMBER);

    // Indigo header band
    doc.setFillColor(ir, ig, ib);
    doc.rect(0, 0, pageWidth, 18, 'F');

    // Amber accent line
    doc.setFillColor(ar, ag, ab);
    doc.rect(0, 18, pageWidth, 1.5, 'F');

    // Title
    doc.setFont(fontName, 'normal');
    doc.setFontSize(13);
    doc.setTextColor(255, 255, 255);
    doc.text('OFAC Screening Compliance Report', 8, 12);

    // Page number + date (right aligned)
    doc.setFontSize(8);
    doc.text(`${now}  |  Page ${pageNumber}`, pageWidth - 8, 12, { align: 'right' });

    // Reset text color
    doc.setTextColor(0, 0, 0);
  }

  // ── Disclaimer footer ────────────────────────────────────────────────────────

  function drawFooter() {
    doc.setFont(fontName, 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(120, 120, 120);
    doc.text(DISCLAIMER, pageWidth / 2, pageHeight - 5, {
      align: 'center',
      maxWidth: pageWidth - 20,
    });
    doc.setTextColor(0, 0, 0);
  }

  // ── Summary block (page 1 only) ───────────────────────────────────────────────

  drawHeader(1);

  const tierCounts: Record<RiskTier, number> = { EXACT: 0, HIGH: 0, MEDIUM: 0, LOW: 0, CLEAR: 0 };
  for (const r of sorted) tierCounts[r.effectiveTier]++;

  doc.setFont(fontName, 'normal');
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text(`Total names screened: ${results.length.toLocaleString()}`, 8, 27);

  let summaryX = 8;
  const tiers: RiskTier[] = ['EXACT', 'HIGH', 'MEDIUM', 'LOW', 'CLEAR'];
  for (const tier of tiers) {
    const [tr, tg, tb] = hexToRgb(TIER_COLORS[tier]);
    doc.setFillColor(tr, tg, tb);
    doc.roundedRect(summaryX, 30, 42, 10, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text(`${tier}  ${tierCounts[tier]}`, summaryX + 21, 36.5, { align: 'center' });
    summaryX += 46;
  }

  doc.setTextColor(0, 0, 0);

  // ── Match records table ───────────────────────────────────────────────────────

  const tableRows = sorted.map((r) => [
    r.inputName,
    r.matchedSdnName,
    `${(r.compositeScore * 100).toFixed(1)}%`,
    r.effectiveTier,
    RECOMMENDED_ACTIONS[r.effectiveTier],
  ]);

  autoTable(doc, {
    head: [['Input Name', 'Matched SDN Name', 'Score', 'Tier', 'Recommended Action']],
    body: tableRows,
    startY: 46,
    margin: { left: 8, right: 8 },
    styles: {
      font: fontName,
      fontSize: 8,
      cellPadding: 2.5,
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: hexToRgb(CROWE_INDIGO),
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 55 },
      2: { cellWidth: 18, halign: 'center' },
      3: { cellWidth: 22, halign: 'center' },
      4: { cellWidth: 'auto' },
    },
    // Color-code the Tier cell per row
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 3) {
        const tier = data.cell.raw as RiskTier;
        if (TIER_COLORS[tier]) {
          data.cell.styles.textColor = hexToRgb(TIER_COLORS[tier]);
          data.cell.styles.fontStyle = 'bold';
        }
      }
    },
    // Draw header + footer on each page
    didDrawPage(hookData) {
      const pageNum = (hookData.pageNumber ?? 1);
      if (pageNum > 1) drawHeader(pageNum);
      drawFooter();
    },
  });

  // Draw footer on page 1 (autoTable only fires didDrawPage for pages it creates after page 1)
  drawFooter();

  doc.save(filename);
}
